<a href="https://colab.research.google.com/github/pariupadhyay15/CODSOFT/blob/main/Housing_prediction(Multiple_regression).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset=pd.read_csv('Housing.csv')
X = dataset.iloc[:, 1:].values
y = dataset.iloc[:, 0].values


In [ ]:
print(X)

[[7420 4 2 ... 2 'yes' 'furnished']
 [8960 4 4 ... 3 'no' 'furnished']
 [9960 3 2 ... 2 'yes' 'semi-furnished']
 ...
 [3620 2 1 ... 0 'no' 'unfurnished']
 [2910 3 1 ... 0 'no' 'furnished']
 [3850 3 1 ... 0 'no' 'unfurnished']]


In [ ]:
print(y)

[13300000 12250000 12250000 12215000 11410000 10850000 10150000 10150000
  9870000  9800000  9800000  9681000  9310000  9240000  9240000  9100000
  9100000  8960000  8890000  8855000  8750000  8680000  8645000  8645000
  8575000  8540000  8463000  8400000  8400000  8400000  8400000  8400000
  8295000  8190000  8120000  8080940  8043000  7980000  7962500  7910000
  7875000  7840000  7700000  7700000  7560000  7560000  7525000  7490000
  7455000  7420000  7420000  7420000  7350000  7350000  7350000  7350000
  7343000  7245000  7210000  7210000  7140000  7070000  7070000  7035000
  7000000  6930000  6930000  6895000  6860000  6790000  6790000  6755000
  6720000  6685000  6650000  6650000  6650000  6650000  6650000  6650000
  6629000  6615000  6615000  6580000  6510000  6510000  6510000  6475000
  6475000  6440000  6440000  6419000  6405000  6300000  6300000  6300000
  6300000  6300000  6293000  6265000  6230000  6230000  6195000  6195000
  6195000  6160000  6160000  6125000  6107500  6090

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4,5,6,7,8,10,11])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[0.0 1.0 1.0 ... 2 3 2]
 [0.0 1.0 1.0 ... 4 4 3]
 [0.0 1.0 1.0 ... 2 2 2]
 ...
 [0.0 1.0 1.0 ... 1 1 0]
 [1.0 0.0 1.0 ... 1 1 0]
 [0.0 1.0 1.0 ... 1 2 0]]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[ 6305417.68  7070000.  ]
 [ 6213853.22  4550000.  ]
 [ 6552975.35  5600000.  ]
 [ 5461129.55  6125000.  ]
 [ 4250945.1   2940000.  ]
 [ 2960943.73  3780000.  ]
 [ 2724161.83  2450000.  ]
 [ 7364540.81  7490000.  ]
 [ 2399155.61  2940000.  ]
 [ 4549456.15  6440000.  ]
 [ 3748550.29  2800000.  ]
 [ 3595286.44  3325000.  ]
 [ 4680228.02  5810000.  ]
 [ 4735410.65  5950000.  ]
 [ 5260666.36  6895000.  ]
 [ 7932596.98 13300000.  ]
 [ 4320848.88  3640000.  ]
 [ 3524363.53  2870000.  ]
 [ 6780229.25  5460000.  ]
 [ 2658354.28  1890000.  ]
 [ 4602977.9   3780000.  ]
 [ 5288794.97  5600000.  ]
 [ 5213197.54  2660000.  ]
 [ 3500380.27  3640000.  ]
 [ 5308434.32  2590000.  ]
 [ 6960288.57  5250000.  ]
 [ 2767308.13  2450000.  ]
 [ 7315992.64  6930000.  ]
 [ 7617590.54  9800000.  ]
 [ 4365295.17  3430000.  ]
 [ 7562556.31  7840000.  ]
 [ 6587921.27  5950000.  ]
 [ 4958237.4   3430000.  ]
 [ 4499776.7   2940000.  ]
 [ 6041408.41  6090000.  ]
 [ 4685509.37  4620000.  ]
 [ 6477135.32  4543000.  ]
 

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.622128043007458